export const EVENT_INTELLIGENCE_STORE = Symbol("EVENT_INTELLIGENCE_STORE");
export const EVENT_INTELLIGENCE_BUS = Symbol("EVENT_INTELLIGENCE_BUS");
export const EVENT_INTELLIGENCE_REPLAY = Symbol("EVENT_INTELLIGENCE_REPLAY");
export const EVENT_INTELLIGENCE_TELEMETRY = Symbol("EVENT_INTELLIGENCE_TELEMETRY");
