"use client";

import { Document, Page, PDFDownloadLink, StyleSheet, Text, View } from "@react-pdf/renderer";
import { Download } from "lucide-react";

import { Button } from "@/components/ui/button";
import { defaultPdfFileName, normalizePdfExportRequest, type PdfExportRequest } from "@/lib/phase-e";

export function PdfDownloadButton({ request }: { request: PdfExportRequest }) {
  const payload = normalizePdfExportRequest(request);
  const fileName = defaultPdfFileName(payload);

  return (
    <PDFDownloadLink document={<VipPdfReport request={payload} />} fileName={fileName}>
      {({ loading }) => (
        <Button
          type="button"
          variant="outline"
          onClick={() => {
            void fetch("/api/admin/system/pdf-export", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(payload),
            });
          }}
        >
          <Download className="size-4" aria-hidden />
          {loading ? "Preparing" : "Export PDF"}
        </Button>
      )}
    </PDFDownloadLink>
  );
}

function VipPdfReport({ request }: { request: PdfExportRequest }) {
  return (
    <Document title={request.title} author="VIP Intelligence OS">
      <Page size="A4" style={styles.page}>
        <Text style={styles.eyebrow}>VIP Intelligence OS</Text>
        <Text style={styles.title}>{request.title}</Text>
        <Text style={styles.meta}>Generated {formatDate(request.generatedAt)}{request.business ? ` · ${request.business}` : ""}</Text>
        {request.summary && <Text style={styles.summary}>{request.summary}</Text>}
        <Section title="KPIs">
          {(request.kpis ?? []).map((kpi) => (
            <View key={`${kpi.label}-${kpi.value}`} style={styles.row}>
              <Text style={styles.rowLabel}>{kpi.label}</Text>
              <Text style={styles.rowValue}>{kpi.value}{kpi.detail ? ` · ${kpi.detail}` : ""}</Text>
            </View>
          ))}
        </Section>
        <Section title="Insights">
          {(request.insights ?? []).map((insight) => <Text key={insight} style={styles.bullet}>- {insight}</Text>)}
        </Section>
        <Section title="Recommendations">
          {(request.recommendations ?? []).map((recommendation) => (
            <View key={recommendation.title} style={styles.card}>
              <Text style={styles.cardTitle}>{recommendation.title}</Text>
              <Text style={styles.cardBody}>{recommendation.summary}</Text>
              {recommendation.evidence && <Text style={styles.cardMeta}>Evidence: {recommendation.evidence}</Text>}
            </View>
          ))}
        </Section>
        <Section title="Action Plan">
          {(request.actionPlan ?? []).map((action) => <Text key={action} style={styles.bullet}>- {action}</Text>)}
        </Section>
        <Section title="Evidence Sources">
          {(request.evidenceSources ?? []).map((source) => <Text key={`${source.label}-${source.source}`} style={styles.bullet}>- {source.label}: {source.source}</Text>)}
        </Section>
        <Text style={styles.footer}>Generated by VIP Intelligence OS</Text>
      </Page>
    </Document>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function formatDate(value?: string) {
  const date = value ? new Date(value) : new Date();
  return date.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: "#0f172a", fontFamily: "Helvetica" },
  eyebrow: { fontSize: 9, color: "#0369a1", textTransform: "uppercase", marginBottom: 8 },
  title: { fontSize: 24, fontWeight: 700, marginBottom: 6 },
  meta: { fontSize: 10, color: "#64748b", marginBottom: 16 },
  summary: { fontSize: 11, lineHeight: 1.5, marginBottom: 18 },
  section: { marginTop: 14 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 8 },
  row: { flexDirection: "row", borderBottom: "1px solid #e2e8f0", paddingVertical: 5 },
  rowLabel: { width: "36%", color: "#475569" },
  rowValue: { width: "64%", fontWeight: 700 },
  bullet: { marginBottom: 5, lineHeight: 1.45 },
  card: { border: "1px solid #e2e8f0", padding: 8, marginBottom: 6 },
  cardTitle: { fontWeight: 700, marginBottom: 4 },
  cardBody: { lineHeight: 1.45 },
  cardMeta: { color: "#475569", marginTop: 4 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, color: "#64748b", fontSize: 9, borderTop: "1px solid #e2e8f0", paddingTop: 8 },
});

