const fs = require('fs')
const path = require('path')
const vm = require('vm')

const repoRoot = path.resolve(__dirname, '..')
const workflowPath = path.join(repoRoot, 'workflows', 'vip_digital_marketing_guarded_test.workflow.js')
const outputPath = path.join(repoRoot, 'frontend', 'src', 'data', 'vipPreviewData.ts')

const workflowSource = fs.readFileSync(workflowPath, 'utf8')
const match = workflowSource.match(/jsCode:\s*`([\s\S]*?)`\s*\n\s*}/)

if (!match) {
  throw new Error('Could not locate workflow Code node jsCode.')
}

const workflowInput = {
  client_slug: 'aayu_geriatrics',
  client_name: 'Aayu Geriatrics',
  engine: 'all',
  test_mode: true,
  disable_writes: true,
  allow_public_fetch: false,
  website_url: 'https://aayugeriatrics.com',
  primary_domain: 'aayugeriatrics.com',
  google_business_profile_url: 'https://www.google.com/search?q=Aayu+Geriatrics',
  service_keywords: [
    'geriatric consultation',
    'elder care',
    'home visit doctor',
    'memory care',
    'fall prevention',
    'chronic disease management',
  ],
  priority_services: [
    'geriatric consultation',
    'home visit doctor',
    'memory care',
  ],
  target_locations: ['Hyderabad', 'Secunderabad', 'Banjara Hills'],
  competitor_names: ['Senior care clinics', 'Home healthcare providers'],
  competitor_websites: ['https://examplehealthcare.com', 'https://exampleeldercare.com'],
  review_platforms: ['Google Business Profile', 'Practo'],
  active_offers: ['First geriatric assessment package'],
  seasonal_campaigns: ['Monsoon senior safety', 'Caregiver awareness week'],
  campaign_goals: ['increase appointment enquiries', 'educate caregivers'],
}

async function runWorkflowCode(jsCode, input) {
  const wrapped = `(async () => { const $json = ${JSON.stringify(input)}; ${jsCode} })()`
  const context = vm.createContext({
    AbortController,
    Boolean,
    console,
    fetch,
    Number,
    Set,
    String,
    TextDecoder,
    URL,
  })

  return vm.runInContext(wrapped, context, { timeout: 15000 })
}

function titleize(value) {
  return String(value || '-')
    .replace(/[_-]/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())
}

function isoDate(offsetDays = 0) {
  const date = new Date()
  date.setUTCDate(date.getUTCDate() + offsetDays)
  return date.toISOString().slice(0, 10)
}

function makeOutput(result, runId, index) {
  return {
    id: `preview-output-${index + 1}`,
    client_id: 'aayu_geriatrics',
    engine_name: result.engine_name,
    source_platform: result.dashboard_section || 'digital',
    report_date: isoDate(0),
    summary: result.summary,
    key_insights: result.findings || [],
    recommendations: result.recommendations || [],
    next_actions: result.next_actions || [],
    confidence_score: result.status === 'success' ? 0.72 : result.status === 'partial_success' ? 0.58 : 0.35,
    input_sources: {
      run_id: runId,
      data_policy: result.data_policy,
      evidence_level: result.evidence_level,
      inputs_used: result.inputs_used,
      remaining_config_needed: result.remaining_config_needed,
      generated_from: 'guarded_digital_marketing_workflow',
    },
    created_at: new Date().toISOString(),
  }
}

function makeContentItem(action, index, sourceEngine) {
  return {
    id: `preview-content-${index + 1}`,
    client_id: 'aayu_geriatrics',
    content_plan_id: 'preview-plan-guarded-digital',
    planned_date: isoDate(index + 1),
    platform: index % 2 === 0 ? 'instagram' : 'facebook',
    content_format: index % 3 === 0 ? 'reel' : 'carousel',
    topic: action.replace(/^(Day \d+:\s*|Create or improve landing coverage for:\s*)/i, ''),
    content_angle: 'Guarded workflow recommendation',
    caption_direction: action,
    creative_brief: 'Use caregiver-first language, clear clinical credibility, and a visible appointment next step.',
    suggested_cta: 'Book a geriatric consultation',
    source_engines: [sourceEngine],
    source_reason: 'Generated by the guarded digital marketing dry run.',
    priority_score: Math.max(55, 90 - index * 4),
    status: index < 2 ? 'production_ready' : 'draft',
    approval_status: index === 0 ? 'pending' : 'needs_review',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
}

function buildPreviewData(workflowResult) {
  const runId = `guarded-digital-${Date.now()}`
  const engineResults = workflowResult.engine_results || []
  const outputs = engineResults.map((result, index) => makeOutput(result, runId, index))
  const strategyActions = workflowResult.strategy_summary?.next_7_day_actions || []
  const recommendationActions = engineResults.flatMap((result) =>
    (result.next_actions || []).map((action) => ({ action, engine: result.engine_name })),
  )
  const items = [
    ...strategyActions.map((action, index) => makeContentItem(action, index, 'digital_marketing_strategy_orchestrator')),
    ...recommendationActions.slice(0, 5).map(({ action, engine }, index) => makeContentItem(action, index + strategyActions.length, engine)),
  ]

  return {
    clients: [
      {
        id: 'aayu_geriatrics',
        client_name: 'Aayu Geriatrics',
        client_slug: 'aayu_geriatrics',
        industry: 'Healthcare',
        location: 'Hyderabad',
        active: true,
      },
    ],
    engineRuns: engineResults.map((result, index) => ({
      id: `${runId}-${index + 1}`,
      client_id: 'aayu_geriatrics',
      engine_name: result.engine_name,
      mode: 'guarded_preview',
      status: result.status,
      started_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      error_message: null,
      metadata: {
        data_policy: result.data_policy,
        evidence_level: result.evidence_level,
        dashboard_section: result.dashboard_section,
      },
    })),
    dailyRuns: [
      {
        id: runId,
        client_id: 'aayu_geriatrics',
        run_date: isoDate(0),
        status: workflowResult.readiness_status?.overall || 'partial_configuration',
        summary: workflowResult.strategy_summary?.summary || workflowResult.workflow_name,
        critical_failure: false,
        started_at: new Date().toISOString(),
        completed_at: new Date().toISOString(),
        engines_completed: engineResults
          .filter((result) => result.status !== 'skipped_missing_config')
          .map((result) => ({ engine: result.engine_name, status: result.status, completed_at: new Date().toISOString() })),
        engines_failed: engineResults
          .filter((result) => result.status === 'skipped_missing_config')
          .map((result) => ({ engine: result.engine_name, status: result.status, error: result.remaining_config_needed?.join(', ') })),
        metadata: {
          workflow_name: workflowResult.workflow_name,
          data_policy: workflowResult.data_policy,
          write_policy: workflowResult.write_policy,
          network_policy: workflowResult.network_policy,
          platform_api_policy: workflowResult.platform_api_policy,
          remaining_config_needed: workflowResult.remaining_config_needed,
        },
      },
    ],
    outputs,
    metrics: [
      ['facebook_intelligence', 'facebook', 'facebook_followers_count', 0],
      ['instagram_intelligence', 'instagram', 'instagram_followers_count', 0],
      ['youtube_intelligence', 'youtube', 'youtube_subscribers_count', 0],
    ].map(([engine, platform, name, value], index) => ({
      id: `preview-metric-${index + 1}`,
      client_id: 'aayu_geriatrics',
      engine_name: engine,
      source_platform: platform,
      metric_date: isoDate(0),
      metric_name: name,
      metric_value: value,
      dimensions: { data_status: 'not_connected_guarded_preview' },
      created_at: new Date().toISOString(),
    })),
    snapshots: [],
    analyticsSummaries: [],
    socialStreaks: [
      {
        id: 'preview-streak-aayu',
        client_id: 'aayu_geriatrics',
        client_slug: 'aayu_geriatrics',
        current_streak: 0,
        longest_streak: 0,
        last_post_date: null,
        last_checked_date: isoDate(0),
        last_status: 'unknown',
        platforms_posted: [],
        post_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    socialStreakLogs: [],
    plans: [
      {
        id: 'preview-plan-guarded-digital',
        client_id: 'aayu_geriatrics',
        plan_type: 'guarded_digital_marketing_preview',
        plan_status: workflowResult.readiness_status?.overall || 'partial_configuration',
        plan_start_date: isoDate(0),
        plan_end_date: isoDate(7),
        strategy_summary: workflowResult.strategy_summary?.top_growth_opportunities?.join(' '),
        source_engines: workflowResult.engines_run || [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    items,
    updates: [
      {
        id: 'preview-update-guarded-digital',
        content_plan_id: 'preview-plan-guarded-digital',
        client_id: 'aayu_geriatrics',
        update_type: 'workflow_rerun',
        update_reason: `Reran ${workflowResult.workflow_name} with writes disabled.`,
        affected_dates: items.map((item) => item.planned_date),
        added_items: items.slice(0, 6).map((item) => item.topic),
        source_engine: 'digital_marketing_strategy_orchestrator',
        created_at: new Date().toISOString(),
      },
    ],
    errors: [
      `Preview data generated from ${workflowResult.workflow_name}; writes and live platform APIs remained disabled.`,
    ],
    previewMeta: {
      ran_at: new Date().toISOString(),
      workflow_name: workflowResult.workflow_name,
      engines_run: workflowResult.engines_run,
      engines_skipped: workflowResult.engines_skipped,
      remaining_config_needed: workflowResult.remaining_config_needed,
      frontend_cards: workflowResult.frontend_cards,
      section_readiness: workflowResult.readiness_status?.by_section,
      top_growth_opportunities: workflowResult.strategy_summary?.top_growth_opportunities,
      next_7_day_actions: workflowResult.strategy_summary?.next_7_day_actions,
    },
  }
}

function serializeModule(data) {
  return `const vipPreviewData = ${JSON.stringify(data, null, 2)} as const\n\nexport default vipPreviewData\n`
}

runWorkflowCode(match[1], workflowInput)
  .then((result) => {
    const workflowResult = result?.json
    if (!workflowResult) throw new Error('Workflow did not return a json payload.')

    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, serializeModule(buildPreviewData(workflowResult)))

    console.log(`Reran ${workflowResult.workflow_name}`)
    console.log(`Generated ${path.relative(repoRoot, outputPath)}`)
    console.log(`Engines run: ${workflowResult.engines_run.map(titleize).join(', ')}`)
  })
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
