import fs from "node:fs/promises";
import path from "node:path";

type ReportEmailAttachment = {
  fileName: string;
  mimeType: string;
  absolutePath: string;
};

type SendReportEmailInput = {
  to: string;
  recipientName?: string | null;
  clientName: string;
  reportTitle: string;
  message?: string | null;
  attachments: ReportEmailAttachment[];
};

export function reportEmailProviderConfigured() {
  return Boolean(process.env.REPORTS_EMAIL_ENABLED === "true" && process.env.RESEND_API_KEY && process.env.REPORTS_FROM_EMAIL);
}

export function reportEmailProviderUnavailableReason() {
  if (process.env.REPORTS_EMAIL_ENABLED !== "true") return "REPORTS_EMAIL_ENABLED is not true; report email was not sent.";
  if (!process.env.RESEND_API_KEY) return "RESEND_API_KEY is missing; report email was not sent.";
  if (!process.env.REPORTS_FROM_EMAIL) return "REPORTS_FROM_EMAIL is missing; report email was not sent.";
  return "Report email provider is not configured.";
}

export async function sendReportEmail(input: SendReportEmailInput) {
  if (!reportEmailProviderConfigured()) {
    throw new Error(reportEmailProviderUnavailableReason());
  }

  const attachments = await Promise.all(input.attachments.map(async (attachment) => ({
    filename: attachment.fileName,
    content: (await fs.readFile(attachment.absolutePath)).toString("base64"),
    contentType: attachment.mimeType,
  })));

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: process.env.REPORTS_FROM_EMAIL,
      reply_to: process.env.REPORTS_REPLY_TO_EMAIL || undefined,
      to: [input.to],
      subject: input.reportTitle,
      text: emailText(input),
      attachments,
    }),
  });

  const body = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(typeof body?.message === "string" ? body.message : `Report email provider failed with ${response.status}.`);
  }

  return typeof body?.id === "string" ? body.id : null;
}

export async function resolveGeneratedReportAttachment(fileUrl: string, fileName: string | null, mimeType: string | null) {
  if (!fileUrl.startsWith("/generated/reports/")) {
    throw new Error("Only generated report export files can be attached.");
  }
  const generatedDir = path.join(process.cwd(), "public", "generated", "reports");
  const safeName = path.basename(fileUrl);
  const absolutePath = path.resolve(generatedDir, safeName);
  const resolvedDir = path.resolve(generatedDir);
  if (!absolutePath.startsWith(resolvedDir)) {
    throw new Error("Invalid report attachment path.");
  }
  await fs.access(absolutePath);

  return {
    fileName: fileName ?? safeName,
    mimeType: mimeType ?? mimeFromName(safeName),
    absolutePath,
  };
}

function emailText(input: SendReportEmailInput) {
  return [
    `Hello${input.recipientName ? ` ${input.recipientName}` : ""},`,
    "",
    input.message?.trim() || `Please find the latest report for ${input.clientName} attached.`,
    "",
    `Report: ${input.reportTitle}`,
    "",
    "Generated by VIP",
  ].join("\n");
}

function mimeFromName(fileName: string) {
  if (fileName.toLowerCase().endsWith(".pdf")) return "application/pdf";
  if (fileName.toLowerCase().endsWith(".docx")) return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  return "application/octet-stream";
}
