import React from "react";
import { Document as DocxDocument, Footer, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { Document, Page, StyleSheet, Text, View, renderToFile } from "@react-pdf/renderer";

import type { ReportDetailResponse, ReportSection } from "./types";
import { REPORT_TYPE_LABELS } from "./types";

export async function renderReportPdf(detail: ReportDetailResponse, filePath: string) {
  await renderToFile(<ReportPdfDocument detail={detail} />, filePath);
}

export async function renderReportDocx(detail: ReportDetailResponse) {
  const doc = new DocxDocument({
    creator: "VIP",
    description: detail.report.summary,
    title: detail.report.title,
    sections: [{
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun("Generated by VIP"),
              ],
            }),
          ],
        }),
      },
      children: [
        heading(detail.report.title, 30),
        paragraph(`Client: ${detail.report.clientName}`),
        paragraph(`Report type: ${REPORT_TYPE_LABELS[detail.report.reportType]}`),
        paragraph(`Business date: ${dateOnly(detail.report.generatedAt ?? detail.report.createdAt)}`),
        paragraph(`Generated: ${dateTime(detail.report.generatedAt ?? detail.report.createdAt)}`),
        paragraph(`Status: ${labelize(detail.report.status)}`),
        heading("Summary", 22),
        paragraph(detail.report.summary || "No summary is available."),
        ...detail.sections
          .slice()
          .sort((left, right) => left.order - right.order)
          .flatMap(renderDocxSection),
        ...renderDocxWarnings(detail.sourceData.missingDataWarnings),
      ],
    }],
  });

  return Packer.toBuffer(doc);
}

function ReportPdfDocument({ detail }: { detail: ReportDetailResponse }) {
  const orderedSections = detail.sections.slice().sort((left, right) => left.order - right.order);

  return (
    <Document title={detail.report.title} author="VIP">
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.eyebrow}>VIP Client Report</Text>
        <Text style={pdfStyles.title}>{detail.report.title}</Text>
        <View style={pdfStyles.metaGrid}>
          <Meta label="Client" value={detail.report.clientName} />
          <Meta label="Report type" value={REPORT_TYPE_LABELS[detail.report.reportType]} />
          <Meta label="Business date" value={dateOnly(detail.report.generatedAt ?? detail.report.createdAt)} />
          <Meta label="Generated" value={dateTime(detail.report.generatedAt ?? detail.report.createdAt)} />
          <Meta label="Status" value={labelize(detail.report.status)} />
        </View>
        <View style={pdfStyles.summary}>
          <Text style={pdfStyles.sectionTitle}>Summary</Text>
          <Text style={pdfStyles.body}>{detail.report.summary || "No summary is available."}</Text>
        </View>
        {orderedSections.map((section) => <PdfSection key={section.id} section={section} />)}
        {detail.sourceData.missingDataWarnings.length ? (
          <View style={pdfStyles.warningBox}>
            <Text style={pdfStyles.warningTitle}>Missing data warnings</Text>
            {detail.sourceData.missingDataWarnings.map((warning) => <Text key={warning} style={pdfStyles.bullet}>- {warning}</Text>)}
          </View>
        ) : null}
        <Text style={pdfStyles.footer} fixed>Generated by VIP</Text>
      </Page>
    </Document>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <View style={pdfStyles.metaItem}>
      <Text style={pdfStyles.metaLabel}>{label}</Text>
      <Text style={pdfStyles.metaValue}>{value}</Text>
    </View>
  );
}

function PdfSection({ section }: { section: ReportSection }) {
  return (
    <View style={pdfStyles.section}>
      <Text style={pdfStyles.sectionTitle}>{section.title}</Text>
      {renderPdfContent(section)}
      {section.sourceRefs?.length ? <Text style={pdfStyles.source}>Sources: {section.sourceRefs.join(", ")}</Text> : null}
    </View>
  );
}

function renderPdfContent(section: ReportSection) {
  const content = section.content;
  if (Array.isArray(content) && content.every((item) => typeof item === "object")) {
    return (
      <View style={pdfStyles.table}>
        {(content as Array<Record<string, string | number | null>>).map((row, index) => (
          <View key={`${section.id}-${index}`} style={pdfStyles.tableRow}>
            <Text style={pdfStyles.tableKey}>{String(row.field ?? row.label ?? `Item ${index + 1}`)}</Text>
            <Text style={pdfStyles.tableValue}>{String(row.value ?? row.summary ?? row.status ?? "")}</Text>
          </View>
        ))}
      </View>
    );
  }
  if (Array.isArray(content)) {
    return <View>{content.map((item) => <Text key={`${section.id}-${item}`} style={pdfStyles.bullet}>- {String(item)}</Text>)}</View>;
  }
  return <Text style={pdfStyles.body}>{String(content || "Not available.")}</Text>;
}

function renderDocxSection(section: ReportSection) {
  return [
    heading(section.title, 22),
    ...renderDocxContent(section),
    ...(section.sourceRefs?.length ? [paragraph(`Sources: ${section.sourceRefs.join(", ")}`, true)] : []),
  ];
}

function renderDocxContent(section: ReportSection) {
  const content = section.content;
  if (Array.isArray(content) && content.every((item) => typeof item === "object")) {
    const rows = (content as Array<Record<string, string | number | null>>).map((row, index) => new TableRow({
      children: [
        new TableCell({ children: [paragraph(String(row.field ?? row.label ?? `Item ${index + 1}`))], width: { size: 32, type: WidthType.PERCENTAGE } }),
        new TableCell({ children: [paragraph(String(row.value ?? row.summary ?? row.status ?? ""))], width: { size: 68, type: WidthType.PERCENTAGE } }),
      ],
    }));
    return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows })];
  }
  if (Array.isArray(content)) {
    return content.map((item) => new Paragraph({ text: String(item), bullet: { level: 0 } }));
  }
  return [paragraph(String(content || "Not available."))];
}

function renderDocxWarnings(warnings: string[]) {
  if (!warnings.length) return [];
  return [
    heading("Missing data warnings", 22),
    ...warnings.map((warning) => new Paragraph({ text: warning, bullet: { level: 0 } })),
  ];
}

function heading(text: string, size: number) {
  return new Paragraph({
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, size })],
  });
}

function paragraph(text: string, muted = false) {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, color: muted ? "64748B" : "0F172A", size: 22 })],
  });
}

function labelize(value: string) {
  return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function dateOnly(value: string) {
  return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));
}

function dateTime(value: string) {
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

const pdfStyles = StyleSheet.create({
  page: { padding: 36, paddingBottom: 54, fontSize: 10, color: "#0f172a", fontFamily: "Helvetica", lineHeight: 1.45 },
  eyebrow: { fontSize: 9, textTransform: "uppercase", color: "#0369a1", marginBottom: 8 },
  title: { fontSize: 24, fontFamily: "Helvetica-Bold", marginBottom: 14 },
  metaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  metaItem: { width: "31%", border: "1 solid #e2e8f0", padding: 8, borderRadius: 4 },
  metaLabel: { fontSize: 7, color: "#64748b", textTransform: "uppercase", marginBottom: 3 },
  metaValue: { fontSize: 9, fontFamily: "Helvetica-Bold" },
  summary: { border: "1 solid #bae6fd", backgroundColor: "#f0f9ff", padding: 10, borderRadius: 4, marginBottom: 10 },
  section: { border: "1 solid #e2e8f0", padding: 10, borderRadius: 4, marginBottom: 10 },
  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", marginBottom: 7 },
  body: { fontSize: 10 },
  bullet: { fontSize: 10, marginBottom: 4 },
  source: { color: "#64748b", fontSize: 7.5, marginTop: 6 },
  table: { border: "1 solid #e2e8f0" },
  tableRow: { flexDirection: "row", borderBottom: "1 solid #e2e8f0" },
  tableKey: { width: "34%", padding: 6, backgroundColor: "#f8fafc", fontFamily: "Helvetica-Bold", fontSize: 8.5 },
  tableValue: { width: "66%", padding: 6, fontSize: 8.5 },
  warningBox: { border: "1 solid #fbbf24", backgroundColor: "#fffbeb", padding: 10, borderRadius: 4, marginTop: 4 },
  warningTitle: { fontSize: 12, fontFamily: "Helvetica-Bold", marginBottom: 6, color: "#92400e" },
  footer: { position: "absolute", left: 36, right: 36, bottom: 24, borderTop: "1 solid #e2e8f0", paddingTop: 8, color: "#64748b", fontSize: 9 },
});
